version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/html/
  - source: /virtualhost.conf
    destination: /etc/apache2/sites-available
hooks:
  AfterInstall:
    - location: scripts/after_install
      runas: ubuntu
