#!/bin/bash
export APACHE_DIR="/etc/apache2"
export WEBSITE_DIR="/var/www/html"
# export CONFIG_FILE_NAME="app2laravel.conf"

export WEB_USER="ubuntu"
export WEB_USER_DATA="www-data"

export SERVER_ADMIN="saasportalweb@gmail.com"
# export SERVER_ADMIN="salestransportes@gmail.com"

export SERVER_NAME=$(wget -qO- ifconfig.me/ip)
export SERVER_ALIAS=$(wget -qO- ifconfig.me/ip)


# //*************************
# 
#   ALTERAR move_upload_file_size no php.ini
# 
# 
#  //************************

sudo apt install php8.1 -y
sudo apt install composer -y

# sudo apt-get install php-curl
# sudo apt-get install php-zip
# sudo apt-get install php-dom
# sudo apt-get install php-xml
# sudo apt-get install php-simplexml  
sudo apt-get install -y php8.1-mysql php8.1-zip php8.1-gd php8.1-mbstring php8.1-curl php8.1-dom php8.1-xml php8.1-gd
sudo /etc/init.d/apache2 restart

cd $APACHE_DIR/sites-available
sudo mv virtualhost.conf app.conf
sudo /etc/init.d/apache2 restart

# sudo cp 000-default.conf $APACHE_DIR/sites-available/$CONFIG_FILE_NAME

# echo "<VirtualHost *:80>" >> $CONFIG_FILE_NAME
# echo "  ServerAdmin $SERVER_ADMIN" >> $CONFIG_FILE_NAME
# echo "  ServerName $SERVER_NAME" >> $CONFIG_FILE_NAME
# echo "  ServerAlias $SERVER_ALIAS" >> $CONFIG_FILE_NAME
# echo "  DocumentRoot $WEBSITE_DIR/public" >> $CONFIG_FILE_NAME
# echo "  <Directory $WEBSITE_DIR>" >> $CONFIG_FILE_NAME
# echo "    Require all granted" >> $CONFIG_FILE_NAME
# echo "    AllowOverride All" >> $CONFIG_FILE_NAME
# echo "    Options Indexes Multiviews FollowSymLinks" >> $CONFIG_FILE_NAME
# echo "  </Directory>" >> $CONFIG_FILE_NAME
# echo "</VirtualHost>" >> $CONFIG_FILE_NAME

# echo "  ErrorLog ${APACHE_LOG_DIR}/error.log" >> $CONFIG_FILE_NAME
# echo "  CustomLog ${APACHE_LOG_DIR}/access.log combined" >> $CONFIG_FILE_NAME

sudo a2dissite 000-default.conf
sudo a2ensite app.conf

# REESCREVENDO MODULO REWRITE
sudo a2enmod rewrite
sudo /etc/init.d/apache2 restart

cd $WEBSITE_DIR

sudo chown -R $WEB_USER:$WEB_USER .
# sudo chown -R www-data storage
# sudo chmod -R u+x .
# sudo chmod -r 777 storage
# sudo chmod -r g+w storage
# sudo chmod -R g+w storage/*
# sudo chmod -R 777 storage/*
# sudo chown -R www-data storage

sudo chmod -R u+x .
sudo chmod -R g+w 777 storage
sudo chmod -R 777 storage/*
sudo chown -R $WEB_USER_DATA:$WEB_USER_DATA storage/*

# instalar dependencias do projeto
# composer install 
composer update

# npm install

php artisan migrate 
php artisan key:generate

sudo /etc/init.d/apache2 restart